site_name: MSA
docs_dir: 'docs/src'
nav:
    - Home: 'index.md'
    - User Manual: 'usermanual.md'
    - API Reference: 'api.md'

theme:
    name: readthedocs
    nav_style: dark
    locale: en
    highlightjs: true
    hljs_languages:
        - python

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.arithmatex:
        generic: true

plugins:
    - search: {}
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    docstring_style: numpy

watch:
    - docs/src
    - msa

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
