site_name: MSA
docs_dir: 'docs/src'
nav:
    - Home: 'index.md'
    - User Manual: 'usermanual.md'
    - API Reference: 'api.md'

theme:
    name: readthedocs
    nav_style: dark
    locale: en
    highlightjs: true
    hljs_languages:
        - python

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        use_pygments: true

plugins:
    - search: {}
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    docstring_style: numpy

watch:
    - docs/src
    - msa
