site_name: MSA
docs_dir: 'docs/src'
nav:
    - Home: 'index.md'
    - API Reference: 'api.md'

theme:
    name: material
    nav_style: dark
    locale: en
    highlightjs: true
    hljs_languages:
        - python

markdown_extensions:
    - toc:
        permalink: true
    - sane_lists: {}
    - admonition: {}
    - pymdownx.highlight:
        use_pygments: true

plugins:
    - search: {}
    - mkdocstrings:
        default_handler: python

watch:
    - docs/src
